FORMAT: 1A
HOST: http://mms.mypetrol.net/

# MMS

Modular Management System API

# Data Structures

### Module (object) - Definition of single module

+ name: divisions (string, required) - Name of the module
+ caption: Střediska (string, required) - Caption of the module
+ hasGrid: true (boolean, required) - Flag saying if the module has grid
+ hasDetail: true (boolean, required) - Flag saying if the module has detail
+ keyField: divisionId (string, required) - Name of field that is primary key
+ categories (array, optional)
    + (Field category)
+ fields (array)
    + (Field)
+ actions (array, optional)
    + (Action)

### Field (object) - Definition of object field
+ name: divisionName (string, required) - Name of the field
+ caption: Název střediska (string, required) - Caption of the field
+ editable: true (boolean, required) - Flag sayin if this field is read only or editable
+ category: 1 (number, optional) - Field category key
+ type: date (Data type, required) - Field data type
+ displayFormat: dd.mm.yyy (string, optional) - Display format
+ decimals: 2 (number, optional) - Number of valid decimal places
+ isInGrid: true (boolean, optional) - Flag saying if this field is in grid, default is false
+ isFilter: true (boolean, optional) - Flag saying if this field can be used to filter data
+ restrictions (Restrictions, optional) - Validating restrictions, value is valid if is empty or all restrictions are fullfiled
+ options (array, optional)
    + (Option)
+ optionsUrl: /api/availableOptions (string, optional) - Url where to obtain available options
+ defaultValue: monday (string, optional) - Default value

### Field category (object) - Sections to categorize fields
+ key: 1 (number, required) - Key which is used to reference category from field
+ caption: Obecné (string, required) - Category caption
+ categories (array, optional)
    + (Field category)

### Option (object) - Available selection option
+ value: monday (string, required) - Value of selected option
+ caption: Pondělí (string, required) - Caption of this option

### Restrictions (object) - Validating restrictions
+ required: true (boolean, optional) - If true, this field cannot be empty
+ minValue: 0 (number, optional) - Minimal value for numbers
+ maxValue: 100 (number, optional) - Maximal value for numbers
+ minValueExclusive: false (boolean, optional) - Flag saying if minValue is inclusive or exclusive, default is false
+ maxValueExclusive: false (boolean, optional) - Flag saying if maxValue is inclusive or exclusive, default is false
+ minLength: 0 (number, optional) - Minimal length of entered value
+ maxLength: 16 (number, optional) - Maximal length of entered value
+ regex: .+@.+\..+ (string, optional) - Regex to validate value
+ invalidLengthMessage: Maximální délka je 16 znaků (string, optional) - Message text when value length is out of bounds
+ invalidValueMessage: Zadaná hodnota není platné datum (string, optional) - Message text when value is out of bounds
+ invalidRegexMessage: Zadaná emailová adresa není platná (string, optional) - Message text when value doesn't match regex pattern

### Action (object) - Actions available in module
+ name: blockDivision (string, required) - Action identifier
+ caption: Blokace střediska (string, required) - Action caption
+ type: block (string, required) - Action type for choosing icon and other behaviour, ie. opening empty detail for new object
+ url: /api/{module}/{id}/{action} (string, required) - Url of this action, available variables are module, id, action for module name, object id based on primary key and action name
+ method: DELETE (string, optional) - Method of HTTP request, default is POST
+ enableFieldName: allowBlockDivision (string, optional) - Based on this field will be action enabled. By default action is enabled
+ message: Přejete si zablokovat středisko {divisionNumber} - {divisionName}? (string, optional) - Message displayed in confirmation dialog, variables are field names
+ enabled: true (boolean, optional) - Flag saying if this action is enabled (ie. if user doesn't have permission)
+ parameters (array) - Parameters to be filled in dialog
    + (Field)
    
### Menu (array) - Applicatin menu
+ (Menu item)

### Menu item (object) - Menu item
+ caption: Střediska (string, required) - Caption of menu item
+ icon: divisions (string, optional) - Icon identifier to be used for this menu item
+ module: divisions (string, optional) - Reference to module by name. Items with subitems do not have module reference
+ items (array, optional) - Collection of menu subitems
    + (Menu item)

### Data type (enum) - Field data types
    + Members
        + number
        + text
        + date
        + time
        + datetime
        + boolean


### Login (object) - Information to authenticate user
+ userName: admin (string, required) - User name
+ password: Password. (string, required) - User password
+ permanent: true (boolean, required) - User will be logged in permanently

# Modules [/api/modules]

### List all modules [GET]

Definition of all modules with all actions and fields.

+ Response 200 (application/json)

    + Attributes (array)
        + (Module)
    
    + Body
    
            [
                {
                  "name": "divisionsBusiness",
                  "caption": "Střediska business",
                  "hasGrid": true,
                  "hasDetail": true,
                  "keyField": "divisionId",
                  "categories" : [
                    {
                        "key": 1,
                        "caption": "Hlavní",
                        "categories": [
                            {
                                "key": 2,
                                "caption": "Obecné"
                            }
                        ]
                    },
                    {
                        "key": 3,
                        "caption": "Aktuální stav"
                    }
                  ],
                  "fields": [
                    {
                      "name": "divisionId",
                      "caption": "Číslo střediska",
                      "editable" : false,
                      "category": 2,
                      "type": "number",
                      "isInGrid": true,
                      "isFilter": true
                    },
                    {
                      "name": "divisionName",
                      "caption": "Název střediska",
                      "editable": true,
                      "category": 2,
                      "type": "text",
                      "isInGrid": true,
                      "isFilter": true,
                      "restrictions": {
                        "required": true,
                        "maxLength": 64
                      }
                    },
                    {
                      "name": "cardCount",
                      "caption": "Počet karet",
                      "editable": false,
                      "category": 3,
                      "type": "number",
                      "isInGrid": true,
                      "isFilter": false
                    }
                  ],
                  "actions": [
                    {
                      "name": "blockDivision",
                      "caption": "Blokace střediska",
                      "type": "block",
                      "url": "/api/{module}/{id}/{action}",
                      "method": "DELETE",
                      "enableFieldName": "allowBlockDivision",
                      "message": "Přejete si zablokovat středisko {divisionNumber}",
                      "enabled": true,
                      "parameters": [
                        {
                          "name": "divisionName",
                          "caption": "Název střediska",
                          "category": "Hlavní",
                          "subcategory": "Obecné",
                          "type": "date",
                          "displayFormat": "dd.mm.yyy",
                          "decimals": 2,
                          "isInGrid": true,
                          "isFilter": true,
                          "restrictions": {
                            "required": true,
                            "minValue": 0,
                            "maxValue": 100,
                            "minValueExclusive": false,
                            "maxValueExclusive": false,
                            "minLength": 0,
                            "maxLength": 16,
                            "regex": ".+@.+..+",
                            "invalidLengthMessage": "Maximální délka je 16 znaků",
                            "invalidValueMessage": "Zadaná hodnota není platné datum",
                            "invalidRegexMessage": "Zadaná emailová adresa není platná"
                          },
                          "options": [
                            {
                              "value": "monday",
                              "caption": "Pondělí"
                            }
                          ],
                          "optionsUrl": "/api/availableOptions",
                          "defaultValue": "monday"
                        }
                      ]
                    }
                  ]
                }
            ]


### Get single module [GET /api/modules/{name}]

Definition of single module with all actions and fields.

+ Parameters
    + name (string, required)

+ Response 200 (application/json)

    + Attributes (Module)
    
    + Body
    
            {
              "name": "divisionsBusiness",
              "caption": "Střediska business",
              "hasGrid": true,
              "hasDetail": true,
              "keyField": "divisionId",
              "categories" : [
                {
                    "key": 1,
                    "caption": "Hlavní",
                    "categories": [
                        {
                            "key": 2,
                            "caption": "Obecné"
                        }
                    ]
                },
                {
                    "key": 3,
                    "caption": "Aktuální stav"
                }
              ],
              "fields": [
                {
                  "name": "divisionId",
                  "caption": "Číslo střediska",
                  "editable" : false,
                  "category": 2,
                  "type": "number",
                  "isInGrid": true,
                  "isFilter": true
                },
                {
                  "name": "divisionName",
                  "caption": "Název střediska",
                  "editable": true,
                  "category": 2,
                  "type": "text",
                  "isInGrid": true,
                  "isFilter": true,
                  "restrictions": {
                    "required": true,
                    "maxLength": 64
                  }
                },
                {
                  "name": "cardCount",
                  "caption": "Počet karet",
                  "editable": false,
                  "category": 3,
                  "type": "number",
                  "isInGrid": true,
                  "isFilter": false
                }
              ],
              "actions": [
                {
                  "name": "blockDivision",
                  "caption": "Blokace střediska",
                  "type": "block",
                  "url": "/api/{module}/{id}/{action}",
                  "method": "DELETE",
                  "enableFieldName": "allowBlockDivision",
                  "message": "Přejete si zablokovat středisko {divisionNumber}",
                  "enabled": true,
                  "parameters": [
                    {
                      "name": "divisionName",
                      "caption": "Název střediska",
                      "category": "Hlavní",
                      "subcategory": "Obecné",
                      "type": "date",
                      "displayFormat": "dd.mm.yyy",
                      "decimals": 2,
                      "isInGrid": true,
                      "isFilter": true,
                      "restrictions": {
                        "required": true,
                        "minValue": 0,
                        "maxValue": 100,
                        "minValueExclusive": false,
                        "maxValueExclusive": false,
                        "minLength": 0,
                        "maxLength": 16,
                        "regex": ".+@.+..+",
                        "invalidLengthMessage": "Maximální délka je 16 znaků",
                        "invalidValueMessage": "Zadaná hodnota není platné datum",
                        "invalidRegexMessage": "Zadaná emailová adresa není platná"
                      },
                      "options": [
                        {
                          "value": "monday",
                          "caption": "Pondělí"
                        }
                      ],
                      "optionsUrl": "/api/availableOptions",
                      "defaultValue": "monday"
                    }
                  ]
                }
              ]
            }

# Menu [/api/menu]

### Get application menu [GET]

Receive menu structure with names of modules

+ Response 200 (application/json)

    + Attributes (Menu)
    
    + Body
    
            [
                {
                    "caption" : "Skupiny zákazníků"
                },
                {
                    "caption" : "Zákazníci",
                    "items" : [
                        {
                            "caption" : "Zákazníci business",
                            "module" : "companyBusiness"
                        },
                        {
                            "caption" : "Zákazníci EASY",
                            "module" : "companyEasy"
                        }
                    ]
                },
                {
                    "caption" : "Střediska",
                    "items" : [
                        {
                            "caption" : "Střediska business",
                            "module" : "divisionsBusiness"
                        },
                        {
                            "caption" : "Střediska EASY",
                            "module" : "divisionsEasy"
                        },
                        {
                            "caption" : "Distributoři",
                            "module" : "distributors"
                        }
                    ]
                },
                {
                    "caption" : "Karty"
                },
                {
                    "caption" : "Účtování"
                },
                {
                    "caption" : "Cenotvorba"
                },
                {
                    "caption" : "Banka"
                },
                {
                    "caption" : "Nastavení"
                },
                {
                    "caption" : "Fleet operátoři"
                },
                {
                    "caption" : "Akceptanti"
                }
            ]


# Login [/api/login]

### Login user [POST]

Authenticate user

+ Attributes (Login)

+ Request (application/json)

+ Response 200

# Logout [/api/logout]

### Logout user [GET]

Logout current user

+ Response 200

# Environment [/api/environment]

### Environment info [GET]

Get environment information like version, theme etc.

+ Response 200 (application/javascript)

    + Body
    
            const environment = {
                caption: "Fleet Management System",
                version: "3.2.15.27",
                locale: {
                    default: "en",
                    available: [
                        {
                            key: "cs",
                            caption: "Česky",
                            countryCode: "cz"
                        },
                        {
                            key: "en",
                            caption: "English",
                            countryCode: "gb"
                        }
                    ]
                },
                theme: {
                    primary: "#3f51b5",
                    secondary: "#f50057"
                }
            }


# Divisions [/api/divisionsBusiness]

### Get divisions [GET]

+ Response 200 (application/json)

    + Headers
            
            X-Total-Count: 30

    + Body
    
            [
                { "divisionId": 16, "divisionName": "Středisko číslo 16", "cardCount": 5 },
                { "divisionId": 17, "divisionName": "Středisko číslo 17", "cardCount": 15 },
                { "divisionId": 18, "divisionName": "Středisko číslo 18", "cardCount": 12 },
                { "divisionId": 19, "divisionName": "Středisko číslo 19", "cardCount": 4 },
                { "divisionId": 20, "divisionName": "Středisko číslo 20", "cardCount": 9 },
                { "divisionId": 21, "divisionName": "Středisko číslo 21", "cardCount": 12 },
                { "divisionId": 22, "divisionName": "Středisko číslo 22", "cardCount": 46 },
                { "divisionId": 23, "divisionName": "Středisko číslo 23", "cardCount": 7 },
                { "divisionId": 24, "divisionName": "Středisko číslo 24", "cardCount": 124 },
                { "divisionId": 25, "divisionName": "Středisko číslo 25", "cardCount": 0 },
                { "divisionId": 26, "divisionName": "Středisko číslo 26", "cardCount": 11 },
                { "divisionId": 27, "divisionName": "Středisko číslo 27", "cardCount": 2 },
                { "divisionId": 28, "divisionName": "Středisko číslo 28", "cardCount": 6 },
                { "divisionId": 29, "divisionName": "Středisko číslo 29", "cardCount": 24 },
                { "divisionId": 30, "divisionName": "Středisko číslo 30", "cardCount": 0 }
            ]